[package]
name = "garbage"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
squirrel-rng = "0.2.0"
stopwatch = "0.0.7"
